package mybatis.dao;

import java.util.List;
import mybatis.model.Game;
import org.mybatis.cdi.Mapper;

@Mapper
public interface GameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    int insert(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    Game selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    List<Game> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    int updateByPrimaryKey(Game record);
}