package mybatis.dao;

import java.util.List;
import mybatis.model.GamePlayer;
import org.mybatis.cdi.Mapper;

@Mapper
public interface GamePlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME_PLAYER
     *
     * @mbg.generated Sat Mar 26 10:46:49 EET 2022
     */
    int insert(GamePlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME_PLAYER
     *
     * @mbg.generated Sat Mar 26 10:46:49 EET 2022
     */
    List<GamePlayer> selectAll();
}