package mybatis.dao;

import java.util.List;

import mybatis.model.Studio;
import org.mybatis.cdi.Mapper;

@Mapper
public interface StudioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDIO
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDIO
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    int insert(Studio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDIO
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    Studio selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDIO
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    List<Studio> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDIO
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    int updateByPrimaryKey(Studio record);

    Studio selectOneByName(String studioName);
}