package mybatis.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class GamePlayer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME_PLAYER.GAMES_ID
     *
     * @mbg.generated Sat Mar 26 10:46:49 EET 2022
     */
    private Integer gamesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME_PLAYER.PLAYERS_ID
     *
     * @mbg.generated Sat Mar 26 10:46:49 EET 2022
     */
    private Integer playersId;
}