package mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class Game {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME.ID
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME.TITLE
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME.STUDIO
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    private Integer studio;

    private List<Player> players;
}