package mybatis.model;

public class Player {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.ID
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYER.HANDLE
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    private String handle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.ID
     *
     * @return the value of PUBLIC.PLAYER.ID
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.ID
     *
     * @param id the value for PUBLIC.PLAYER.ID
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYER.HANDLE
     *
     * @return the value of PUBLIC.PLAYER.HANDLE
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    public String getHandle() {
        return handle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYER.HANDLE
     *
     * @param handle the value for PUBLIC.PLAYER.HANDLE
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    public void setHandle(String handle) {
        this.handle = handle;
    }
}