package mybatis.model;

public class Studio {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDIO.ID
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDIO.CITY
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDIO.NAME
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDIO.ID
     *
     * @return the value of PUBLIC.STUDIO.ID
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDIO.ID
     *
     * @param id the value for PUBLIC.STUDIO.ID
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDIO.CITY
     *
     * @return the value of PUBLIC.STUDIO.CITY
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDIO.CITY
     *
     * @param city the value for PUBLIC.STUDIO.CITY
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDIO.NAME
     *
     * @return the value of PUBLIC.STUDIO.NAME
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDIO.NAME
     *
     * @param name the value for PUBLIC.STUDIO.NAME
     *
     * @mbg.generated Fri Mar 25 21:15:25 EET 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}